vim.keymap.set("n", "]c", "<Plug>GitDiffNextHunk")
vim.keymap.set("n", "[c", "<Plug>GitDiffPrevHunk")
vim.keymap.set("n", "gh", "<Plug>GitDiffResetHunk")
vim.keymap.set("v", "gh", "<Plug>GitDiffResetHunk")
vim.keymap.set("n", "gH", "<Plug>GitDiffResetFile")
