vim.keymap.set("n", "]h", "<Plug>GitDiffNextHunk")
vim.keymap.set("n", "[h", "<Plug>GitDiffPrevHunk")
vim.keymap.set("n", "gh", "<Plug>GitDiffResetHunk")
vim.keymap.set("v", "gh", "<Plug>GitDiffResetHunk")
vim.keymap.set("n", "gH", "<Plug>GitDiffResetFile")
