require "settings.plugins.packer"

require "settings.plugins.bufferline"
require "settings.plugins.bqf"
require "settings.plugins.coc"
require "settings.plugins.comment"
require "settings.plugins.commentstring"
require "settings.plugins.diffview"
require "settings.plugins.harpoon"
require "settings.plugins.indent"
require "settings.plugins.leap"
require "settings.plugins.lualine"
require "settings.plugins.neoclip"
require "settings.plugins.node_action"
require "settings.plugins.scrollbar"
require "settings.plugins.tele"
require "settings.plugins.tree"
require "settings.plugins.treesitter"
